name: C++ Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlcppconn-dev libssl-dev libboost-all-dev

    - name: Set up CMake 3.24
      uses: borgar/setup-cmake@v2
      with:
        cmake-version: '3.24'

    - name: Build Debug
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        cmake --build .
